name: CI Pipeline for SonarQube

on:
  push:
    branches:
      - main  # Déclenche le pipeline lors d'un push sur la branche principale

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout du code
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Configuration de Java (assurez-vous que Java est installé)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Installation des dépendances et compilation du projet (par exemple, avec Gradle)
      - name: Build with Gradle
        run: ./gradlew build

      # Exécution des tests unitaires
      - name: Run unit tests
        run: ./gradlew test

      # Exécution de SonarQube Scanner
      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token SonarQube en tant que secret GitHub
        run: ./gradlew sonarqube \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.host.url=https://your-sonarqube-url \
              -Dsonar.login=$SONAR_TOKEN