name: SonarQube Gradle

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      # Checkout du code source
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      # Configuration de l'environnement JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu' 

      # Install dependencies 
   
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip

      # Clean cache
      - name: Clean caches 
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.sonar/cache

      # Mise en cache des paquets SonarQube
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Mise en cache des paquets Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle


      # permissions d'exécution à gradlew
      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x ./gradlew
        
      - name: Use Gradle Wrapper
        run: ./gradlew wrapper 
            
      
      # Compilation et analyse avec SonarQube
      - name: Build, test and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonarqube --info --stacktrace
#add for test
          
      # Compression du log de build for debug 
      - name: Compress Build Log
        run: gzip -9 build.log || echo "No build.log found"

      # Upload du build log en tant qu'artifact
      - name: Upload Build Log Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log.gz
          retention-days: 7
